spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    generate-ddl: false
    properties:
      hibernate.generate_statistics: true
  datasource:
    url: jdbc:postgresql://localhost:5532/alerts
    username: xxxx
    password: xxxx
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql: trace


url: https://polisen.se/api/events
