spring:
  jpa:
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/bar
    username: xxxx
    password: xxxx
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false
