spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    generate-ddl: false
    properties:
      hibernate.generate_statistics: true
  datasource:
      url: jdbc:postgresql://localhost:5532/alerts
      username: xxxx
      password: xxxx
      driver-class-name: org.postgresql.Driver