spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5532/alerts
    username: xxxx
    password: xxxx
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false
